version: "3.5"
services:
    frontend:
       image: "jino-trader-frontend"
       build: ./frontend
       ports:
          - "8080:80" 
    backend:
       image: "jino-trader-backend"
       build: ./backend
       ports:
          - "8081:80"
       networks:
          - messaging
       depends_on:
          - backend-database
          - queue
    backend-database:
       image: "postgres:14.2"
       ports:
          - "5500:5443"
       volumes:
          - postgres-backend-data:/home/postgres/data
    loader:
       image: "jino-trader-loader"
       build: ./loader
       networks:
          - messaging
       depends_on:
          - loader-database
          - queue    
    loader-database:
       image: "postgres:14.2"
       ports:
          - "5500:5443"
       volumes:
          - loader-postgres-data:/home/postgres/data   
    queue:
        image: "jino-trader-queue"
        build: ./queue
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - messaging

networks: 
    messaging:
      driver: bridge

volumes:
    backend-postgres-data:
    loader-postgres-data:
    queue-data:
